// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJEUR2-d72FpwBvibttwv57bKPMHvVYDA',
    appId: '1:780853414578:web:a379289d279d12c05317ab',
    messagingSenderId: '780853414578',
    projectId: 'vox-manus',
    authDomain: 'vox-manus.firebaseapp.com',
    storageBucket: 'vox-manus.firebasestorage.app',
    measurementId: 'G-BHXTTHKHXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARjfoj9IEom8ADsdpLb8Rcp51_9Qg4EoA',
    appId: '1:780853414578:android:0317dc2b8e10a3465317ab',
    messagingSenderId: '780853414578',
    projectId: 'vox-manus',
    storageBucket: 'vox-manus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjPUfZ780uE8SzBq45YDnDRaKYKnmov08',
    appId: '1:780853414578:ios:7380d00db3092bbb5317ab',
    messagingSenderId: '780853414578',
    projectId: 'vox-manus',
    storageBucket: 'vox-manus.firebasestorage.app',
    androidClientId: '780853414578-ijahn00qrva75pr8aaftcmv8mp7jdcmr.apps.googleusercontent.com',
    iosClientId: '780853414578-lbfoc0u0j6u7jipnbnv4p0d62m20ma8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjPUfZ780uE8SzBq45YDnDRaKYKnmov08',
    appId: '1:780853414578:ios:7380d00db3092bbb5317ab',
    messagingSenderId: '780853414578',
    projectId: 'vox-manus',
    storageBucket: 'vox-manus.firebasestorage.app',
    androidClientId: '780853414578-ijahn00qrva75pr8aaftcmv8mp7jdcmr.apps.googleusercontent.com',
    iosClientId: '780853414578-lbfoc0u0j6u7jipnbnv4p0d62m20ma8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJEUR2-d72FpwBvibttwv57bKPMHvVYDA',
    appId: '1:780853414578:web:3114982aed514b355317ab',
    messagingSenderId: '780853414578',
    projectId: 'vox-manus',
    authDomain: 'vox-manus.firebaseapp.com',
    storageBucket: 'vox-manus.firebasestorage.app',
    measurementId: 'G-KZMCST32LL',
  );

}